services:
  nginx:
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
      - /home/rumachad/logs:/var/log/nginx
    networks:
      - internal
  wordpress:
    image: worpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
    networks:
      - internal
    env_file:
      - .env
  mariadb:
    image: mariadb
    build: requirements/mariadb
    volumes:
      - /home/rumachad/data/db:/var/lib/mysql
    networks:
      - internal
    env_file:
      - .env
networks:
  internal:
    driver: bridge
