services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - internal
    secrets:
      - ssl_key
      - ssl_crt
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - internal
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_pass
      - wp_admin_pass
      - wp_user_pass
    restart: always
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_db:/var/lib/mysql
    networks:
      - internal
    env_file:
      - .env
    secrets:
      - db_pass
    restart: always

volumes:
  mariadb_db:
    driver: local
    driver_opts:
      type: none
      device: /home/rumachad/data/db
      o: bind
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/rumachad/data/wordpress
      o: bind

networks:
  internal:
    driver: bridge

secrets:
  db_pass:
    file: ../secrets/db_password
  wp_admin_pass:
    file: ../secrets/wp_password
  wp_user_pass:
    file: ../secrets/wp_user_password
  ssl_key:
    file: ../secrets/tls/localhost.key
  ssl_crt:
    file: ../secrets/tls/localhost.crt
