services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
      - /home/rumachad/logs:/var/log/nginx
    networks:
      - internal
    secrets:
      - ssl_key
      - ssl_crt
    restart: on-failure
  wordpress:
    image: worpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
    networks:
      - internal
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_pass
      - wp_pass
    restart: on-failure
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - /home/rumachad/data/db:/var/lib/mysql
    networks:
      - internal
    env_file:
      - .env
    secrets:
      - db_pass
    restart: on-failure
networks:
  internal:
    driver: bridge
secrets:
  db_pass:
    file: ../secrets/db_password
  wp_pass:
    file: ../secrets/wp_password
  ssl_key:
    file: ../secrets/tls/localhost.key
  ssl_crt:
    file: ../secrets/tls/localhost.crt
