services:
  nginx:
    image: mynginx
    build: requirements/nginx
    ports:
      - "8080:80"
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
      - /home/rumachad/logs:/var/log/nginx
    networks:
      - internal
  wordpress:
    image: worpress
    build: requirements/wordpress
    volumes:
      - /home/rumachad/data/wordpress:/var/www/html
    networks:
      - internal
  mariadb:
    image: mariadb
    build: requirements/mariadb
    volumes:
      - /home/rumachad/data/db:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
